### ISSUE TITLE
Is Electron workaround still necessary?

### ISSUE THREAD

**Issue by christianbundy** [dominictarr/chloride#20]
There's an Electron workaround in `index.js` that was added in July 2016, which was before Electron 1.3 was released (Chrome 52, Node 6). Four years later Electron is on version 10.11, and I've tested all the way back to Electron 7 and I can't find the problem. Does anyone have more context on what platform the problem was happening on? The only context I have is https://github.com/ssb-js/chloride/commit/50dbe3bfdf3973cc4a6e7d8f2d00c24329710b06, but that doesn't tell us much.

If the underlying problem is gone, I'd love to remove the workaround, but I thought I should make an issue before making a PR.

**Comment by arj03** [comment]
I don't see why that should be there still. Lets Get It Removed :-)

**Comment by austinfrey** [comment]
@christianbundy I did some tests going all the way back to [electron v1](https://github.com/austinfrey/chloride-is-electron-test). Things break around v3 but not due to the `detached` methods I don't think.
