### ISSUE TITLE
Replace sodium-prebuilt with sodium-native

### ISSUE THREAD

**Issue by yangwao** [dominictarr/chloride#4]
When I wanted to install scuttlebot, there was numerous problems to install sodium-prebuilt package on Darwin without automake and libtool. 
Recommended solution from @mafintosh https://github.com/mafintosh/node-sodium-prebuilt/issues/10#issuecomment-293849292 is to replace package for sodium-native

Thoughts?

**Comment by dominictarr** [comment]
yes, so we basically just need either to update secret-handshake, private-box, ssb-keys and pull-box-stream to the sodium-native api. or write an adapter that gives the other api. pull-box-stream is the only place that would actually benefit from the memory reusing perf thing

**Comment by ralphtheninja** [comment]
Just tried installing scuttlebot and the installation is super fast! :heart:

This issue can be closed. I believe `2.2.7` fixes this but the code isn't pushed to github yet.

**Comment by dominictarr** [comment]
yup, this is all good now, and there is even a prebuild for arm (RPi and your phone)

**Comment by clehner** [comment]
This is done since v2.2.7 52ae4f7edec8148de9065f77d6c256b9710a923c
